In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/book_data.csv")

In [3]:
df.head()

,book_authors,book_desc,book_edition,book_format,book_isbn,book_pages,book_rating,book_rating_count,book_review_count,book_title,genres,image_url
0,Suzanne Collins,Winning will make you famous. Losing means cer...,NaN,Hardcover,9.78044E+12,374 pages,4.33,5519135,160706,The Hunger Games,Young Adult|Fiction|Science Fiction|Dystopia|F...,https://images.gr-assets.com/books/1447303603l...
1,J.K. Rowling|Mary GrandPré,There is a door at the end of a silent corrido...,US Edition,Paperback,9.78044E+12,870 pages,4.48,2041594,33264,Harry Potter and the Order of the Phoenix,Fantasy|Young Adult|Fiction,https://images.gr-assets.com/books/1255614970l...
2,Harper Lee,The unforgettable novel of a childhood in a sl...,50th Anniversary,Paperback,9.78006E+12,324 pages,4.27,3745197,79450,To Kill a Mockingbird,Classics|Fiction|Historical|Historical Fiction...,https://images.gr-assets.com/books/1361975680l...
3,Jane Austen|Anna Quindlen|Mrs. Oliphant|George...,«È cosa ormai risaputa che a uno scapolo in po...,"Modern Library Classics, USA / CAN",Paperback,9.78068E+12,279 pages,4.25,2453620,54322,Pride and Prejudice,Classics|Fiction|Romance,https://images.gr-assets.com/books/1320399351l...
4,Stephenie Meyer,About three things I was absolutely positive.F...,NaN,Paperback,9.78032E+12,498 pages,3.58,4281268,97991,Twilight,Young Adult|Fantasy|Romance|Paranormal|Vampire...,https://images.gr-assets.com/books/1361039443l...

In [4]:
df.duplicated().value_counts()

False    54301
dtype: int64

In [5]:
df.isna().sum()

book_authors             0
book_desc             1331
book_edition         48848
book_format           1656
book_isbn            12866
book_pages            2522
book_rating              0
book_rating_count        0
book_review_count        0
book_title               0
genres                3242
image_url              683
dtype: int64

In [6]:
df.describe()

        book_rating  book_rating_count  book_review_count
count  54301.000000       5.430100e+04        54301.00000
mean       4.020027       4.350449e+04         2011.60218
std        0.362100       2.126572e+05         7627.07287
min        0.000000       0.000000e+00            0.00000
25%        3.830000       4.070000e+02           35.00000
50%        4.030000       2.811000e+03          188.00000
75%        4.220000       1.274500e+04          822.00000
max        5.000000       5.588580e+06       160776.00000

In [7]:
df.image_url[0]

'https://images.gr-assets.com/books/1447303603l/2767052.jpg'

In [8]:
df = df.drop(columns=["book_edition","book_format","book_isbn","book_review_count"])

In [9]:
df.head()

,book_authors,book_desc,book_pages,book_rating,book_rating_count,book_title,genres,image_url
0,Suzanne Collins,Winning will make you famous. Losing means cer...,374 pages,4.33,5519135,The Hunger Games,Young Adult|Fiction|Science Fiction|Dystopia|F...,https://images.gr-assets.com/books/1447303603l...
1,J.K. Rowling|Mary GrandPré,There is a door at the end of a silent corrido...,870 pages,4.48,2041594,Harry Potter and the Order of the Phoenix,Fantasy|Young Adult|Fiction,https://images.gr-assets.com/books/1255614970l...
2,Harper Lee,The unforgettable novel of a childhood in a sl...,324 pages,4.27,3745197,To Kill a Mockingbird,Classics|Fiction|Historical|Historical Fiction...,https://images.gr-assets.com/books/1361975680l...
3,Jane Austen|Anna Quindlen|Mrs. Oliphant|George...,«È cosa ormai risaputa che a uno scapolo in po...,279 pages,4.25,2453620,Pride and Prejudice,Classics|Fiction|Romance,https://images.gr-assets.com/books/1320399351l...
4,Stephenie Meyer,About three things I was absolutely positive.F...,498 pages,3.58,4281268,Twilight,Young Adult|Fantasy|Romance|Paranormal|Vampire...,https://images.gr-assets.com/books/1361039443l...

In [10]:
def listed(x):
    if type(x) != str:
        return x
    return x.split("|")

In [11]:
df["book_authors"] = df["book_authors"].apply(listed)

In [12]:
df["genres"] = df["genres"].apply(listed)

In [13]:
df["genres"]

0        [Young Adult, Fiction, Science Fiction, Dystop...
1                          [Fantasy, Young Adult, Fiction]
2        [Classics, Fiction, Historical, Historical Fic...
3                             [Classics, Fiction, Romance]
4        [Young Adult, Fantasy, Romance, Paranormal, Va...
                               ...
54296    [Sports, Baseball, Sports and Games, Sports, N...
54297               [Nonfiction, Sports and Games, Sports]
54298                        [Sports, Baseball, Abandoned]
54299    [Nonfiction, Autobiography, Memoir, Biography,...
54300    [Criticism, Literary Criticism, Philosophy, Th...
Name: genres, Length: 54301, dtype: object

In [14]:
def pages(x):
    if type(x)==str:
        if "pages" in x:
            return float(x[:-6])
        return float(x[:-5])
    return x

In [15]:
df["book_pages"] = df["book_pages"].apply(pages)

In [16]:
df.loc[df["book_pages"]==0]

,book_authors,book_desc,book_pages,book_rating,book_rating_count,book_title,genres,image_url
1318,[Ayn Rand],The bestselling novels from the foremost philo...,0.0,4.09,4265,Atlas Shrugged & The Fountainhead,"[Fiction, Classics, Philosophy, Literature, Po...",https://images.gr-assets.com/books/1159932401l...
2851,[Angelo Tsanatelis],He appeared seemingly out of nowhere. They wer...,0.0,4.31,32,The Rootless,"[Fantasy, Dark Fantasy, Fantasy]",https://images.gr-assets.com/books/1344245300l...
3175,[Jean M. Auel],"Boxed set includes The Mammoth Hunters, The Va...",0.0,4.27,4889,"The Clan of the Cave Bear, the Valley of Horse...","[Historical, Historical Fiction, Fiction, Fant...",https://images.gr-assets.com/books/1235059058l...
4026,[Benjamin Hoff],Who would have though that Winnie-the-Pooh and...,0.0,4.15,10206,Tao of Pooh and Te of Piglet Boxed Set,"[Spirituality, Philosophy, Nonfiction, Psychol...",https://images.gr-assets.com/books/1444316923l...
4310,[C.S. Lewis],The Cosmic Trilogy relates the interplanetary ...,0.0,4.11,8069,Space Trilogy: Out of the Silent Planet / Pere...,"[Science Fiction, Fiction, Fantasy, Christian,...",https://images.gr-assets.com/books/1386924691l...
...,...,...,...,...,...,...,...,...
53469,[Elizabeth Goudge],Michael Stone was once a famous author. That w...,0.0,4.10,425,The Rosemary Tree,"[Fiction, Romance, European Literature, Britis...",https://images.gr-assets.com/books/1259397869l...
53477,[Idries Shah],"This CD set is a recording of a live lecture, ...",0.0,4.83,12,Overcoming Assumptions That Inhibit Spiritual ...,NaN,https://images.gr-assets.com/books/1266822216l...
53646,[Al Dempster],Inspired by a 1932 Walt Disney Silly Symphony ...,0.0,4.30,3402,Santa's Toy Shop (A Little Golden Book),"[Holiday, Christmas, Childrens, Childrens, Pic...",https://images.gr-assets.com/books/1342467319l...
54032,[David Ambrose],"Tessa Lambert sits in a hotel room, alone and ...",0.0,3.28,144,Mother of God,"[Science Fiction, Fiction, Thriller]",https://images.gr-assets.com/books/1179201282l...
54182,[Cheri Schmidt],The Fateful Trilogy continues with Fractured. ...,0.0,3.99,855,Fractured,"[Paranormal, Vampires, Fantasy, Paranormal, Yo...",https://images.gr-assets.com/books/1307123795l...

In [38]:
df.shape

(54108, 8)

In [39]:
df.describe()

         book_pages   book_rating  book_rating_count
count  51586.000000  54108.000000       5.410800e+04
mean     338.926143      4.019962       4.362762e+04
std      259.193395      0.361482       2.129935e+05
min        1.000000      0.000000       0.000000e+00
25%      218.000000      3.830000       4.100000e+02
50%      310.000000      4.030000       2.825000e+03
75%      400.000000      4.220000       1.279175e+04
max    14777.000000      5.000000       5.588580e+06

In [40]:
df.head()

,book_authors,book_desc,book_pages,book_rating,book_rating_count,book_title,genres,image_url
0,[Suzanne Collins],Winning will make you famous. Losing means cer...,374.0,4.33,5519135,The Hunger Games,"[Young Adult, Fiction, Science Fiction, Dystop...",https://images.gr-assets.com/books/1447303603l...
1,"[J.K. Rowling, Mary GrandPré]",There is a door at the end of a silent corrido...,870.0,4.48,2041594,Harry Potter and the Order of the Phoenix,"[Fantasy, Young Adult, Fiction]",https://images.gr-assets.com/books/1255614970l...
2,[Harper Lee],The unforgettable novel of a childhood in a sl...,324.0,4.27,3745197,To Kill a Mockingbird,"[Classics, Fiction, Historical, Historical Fic...",https://images.gr-assets.com/books/1361975680l...
3,"[Jane Austen, Anna Quindlen, Mrs. Oliphant, Ge...",«È cosa ormai risaputa che a uno scapolo in po...,279.0,4.25,2453620,Pride and Prejudice,"[Classics, Fiction, Romance]",https://images.gr-assets.com/books/1320399351l...
4,[Stephenie Meyer],About three things I was absolutely positive.F...,498.0,3.58,4281268,Twilight,"[Young Adult, Fantasy, Romance, Paranormal, Va...",https://images.gr-assets.com/books/1361039443l...

In [42]:
df.to_csv("data/book_processed_data.csv")